(function(g){var window=this;'use strict';var h1=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},i1=function(a){return g.gB(a)&&!a.K("web_player_i_see_captions_3_killswitch")},iXa=function(a,b){var c,d,e;
return g.B(function(f){if(1==f.j)return c=a+"|"+b,g.A(f,g.Rr(),2);if(3!=f.j){d=f.u;if(!d)throw g.rr("gct");return g.A(f,g.zC(d),3)}e=f.u;return f.return(e.get("captions",c))})},jXa=function(a,b){var c=new g.CC;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},kXa=function(a,b,c){iXa(a,b).then(function(d){d&&c(d.trackData,new g.CC(d.metadata))})},j1=function(){this.segments=[]},lXa=function(a,b){var c=g.Wb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Nb(a.segments,c),g.Nb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Ub(a.segments,c,0,b),g.Ub(a.segments,c+1,0,b)))},k1=function(a,b,c,d,e,f){g.I.call(this);
this.policy=a;this.player=b;this.V=c;this.P=d;this.D=e;this.U=f;this.environmentData=this.player.S();this.C=new j1;this.I=-1;this.B=this.u=this.j=null;this.J=new g.K(this.WO,1E3,this);this.events=new g.Vy(this);g.J(this,this.J);g.J(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.CC);this.CC();this.WO()},mXa=function(a){return a.j&&a.j.C?a.j.C+a.player.pd()<a.player.getCurrentTime():!1},nXa=function(a,b){var c=g.Tx(g.py(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.$p(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,k=g.Fua(e);if(k){e=g.py(a.u,a.policy,{});a.u.Ik(e,k);nXa(a,a.u);break a}f?a.player.qa("capfail",{status:e.status}):(a.player.Qi().po("fcb_r"),k=a.u.j[0].Ha,null!=a.P&&a.I!==k&&(f=a.u.j[0],a.D?a.P(e.response,1E3*(f.startTime+a.player.pd())):a.P(e.responseText,1E3*(f.startTime+a.player.pd())),a.I=k))}a.u=null;a.B=null}}).Ii(function(e){a.u=
null;
a.B=null;var f;a.player.qa("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;lXa(a.C,a.u.j[0].Ha)},l1=function(a,b){g.KI.call(this,b.S());
this.j=a;this.G=b;this.B=null;this.D=!1;this.I=g.iB(this.G.S())&&!this.j.isManifestless},pXa=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.MI(e,b||null)){var f=e.info.id,k=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.AVa.get(e);null==n&&(n=oXa[e]||oXa[e.replace(/-/g,"_")],g.AVa.set(e,n));k=n||k}c.push(new g.CC({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},qXa=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},rXa=function(a,b,c){var d=
[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.MI(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode===b&&d.push(f)}}return d.length?d[0]:null},m1=function(a){if(!sXa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(tXa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},n1=function(a,b,c,d,e,f,k,l){var m={};
Object.assign(m,b);Object.assign(m,a.params);Object.assign(m,c);var n={};Object.assign(n,b.Kd);a.params.Kd&&Object.assign(n,a.params.Kd);Object.assign(n,c.Kd);m.Kd=n;g.V.call(this,{F:"div",L:"caption-window",T:{id:"caption-window-"+a.id,dir:1===m.Mg?"rtl":"ltr",tabindex:"0",lang:m.lang},R:[{F:"span",L:"captions-text",T:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.ma=!1;this.u=a;this.Ca=this.xa=null;this.playerWidth=f;this.playerHeight=k;this.I=null;this.maxWidth=.96*f;this.maxHeight=
.96*k;this.j=m;this.Gb=c;this.Ga=b;this.C=this.va("captions-text");this.ib=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.V=e/360*16;!l.bb("web_player_scale_font_size_for_shorts_killswitch")&&e>=d&&(this.V=f/640*16);this.type=0;this.Qa=this.V*uXa(n);a=new g.Yt(this.element,!0);g.J(this,a);a.subscribe("dragstart",this.IU,this);a.subscribe("dragmove",this.HU,this);a.subscribe("dragend",this.GU,this);this.Ya=this.Sa=
0;b="";this.j.windowOpacity&&(a=m1(this.j.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");a={"background-color":b,display:!1===this.j.isVisible?"none":"","text-align":vXa[this.j.textAlign]};this.ib&&(a["border-radius"]=b?this.Qa/8+"px":"");if(this.B=2===this.u.params.Mg||3===this.u.params.Mg)b=this.element,c="vertical-rl",1===this.j.MJ&&(c="vertical-lr"),g.mc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Bk(b,"-o-writing-mode",c),g.Bk(b,"-webkit-writing-mode",c),g.Bk(b,"writing-mode",
c),g.Bk(b,"text-orientation","upright"),g.vn(b,"ytp-vertical-caption"),3===this.u.params.Mg&&(g.Bk(b,"text-orientation",""),g.Bk(b,"transform","rotate(180deg)"));g.Bk(this.element,a);switch(this.j.yj){case 0:case 1:case 2:g.vn(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.vn(this.element,"ytp-caption-window-bottom")}},uXa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},wXa=function(a,b){var c={},d=b.background?b.background:a.j.Kd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Kd.backgroundOpacity;d=m1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ib&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Qa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.V*uXa(b)+"px";d=1;e=b.color||a.j.Kd.color;if(b.color||null!=b.textOpacity)e=m1(e),d=null==b.textOpacity?a.j.Kd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.DF&&(k=e=b.DF);var l=a.V/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.jq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Kd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.mX&&(c.visibility="hidden");1===b.pO&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.mB||g.pr,3===a.u.params.Mg?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Yk||2===b.Yk||3===b.Yk||4===b.Yk||5===b.Yk)if(g.mB)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Yk){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},xXa=function(a){a.I=g.ig("SPAN");
g.Bk(a.I,{display:"block"});g.vn(a.I,"caption-visual-line");a.C.appendChild(a.I)},yXa=function(a,b){var c=g.ig("SPAN");
g.Bk(c,{display:"inline-block","white-space":"pre-wrap"});g.Bk(c,wXa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.Bk(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Bk(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},zXa=function(a,b,c){a.ma=a.ma||!!c;
var d={};Object.assign(d,a.j.Kd);Object.assign(d,c||b.j);Object.assign(d,a.Gb.Kd);(c=!a.I)&&xXa(a);for(var e=a.xa&&a.Ca&&g.De(d,a.Ca)?a.xa:yXa(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.append,n=k[l];m&&!c?(xXa(a),e=yXa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.jg(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.mB||!g.Gk(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Gk(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.je?g.Bk(e,m,"1em"):g.Bk(e,m,"0.5em")))}a.Ca=d;a.xa=e;a.D.push(b)},o1=function(a,b,c,d){g.KI.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ma=d;this.C=b.dF},p1=function(a,b,c,d,e,f,k,l){n1.call(this,a,b,c,d,e,f,k,l);
this.type=1},q1=function(a,b,c,d,e,f,k,l){n1.call(this,a,b,c,d,e,f,k,l);
this.type=2;this.J=[];this.U=this.P=this.Ka=0;this.ea=NaN;this.Za=0;this.sb=null;this.Pa=new g.K(this.k_,433,this);g.vn(this.element,"ytp-caption-window-rollup");g.J(this,this.Pa);g.Bk(this.element,"overflow","hidden")},AXa=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.MJ&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},BXa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.rowCount,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.P=d;b=Math;c=b.max;isNaN(a.ea)&&((d=a.j.Po)?(e=g.ig("SPAN"),g.pg(e,"\u2013".repeat(d)),g.Bk(e,wXa(a,a.j.Kd)),a.C.appendChild(e),a.ea=e.offsetWidth,a.C.removeChild(e)):a.ea=0);d=a.C;a.U=c.call(b,a.ea,a.Za,(a.B?d.offsetHeight:d.offsetWidth)+1)},CXa=function(a,b){BXa(a);
var c=a.J.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.P-c;if(c!==a.Ka){var d=0<c&&0===a.Ka;b||isNaN(c)||d||(g.vn(a.element,"ytp-rollup-mode"),g.on(a.Pa));g.Bk(a.C,"transform",AXa(a,c));a.Ka=c}BXa(a)},r1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.kv.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=k},s1=function(a,b,c,d,e){g.kv.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},DXa=function(a){var b="_"+t1++;
return new s1(0,0x8000000000000,0,b,a)},FXa=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1===m.Qe){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[p.getAttribute("p")];l=EXa(l.textContent,n.textContent,p.textContent,f.textContent,k);return new r1(a,b,e,c,l,d,m)}switch(m.Qe){case 9:case 10:m.Yk=1;break;case 11:m.Yk=2;break;case 12:m.Yk=3;break;case 13:m.Yk=4;break;case 14:m.Yk=5}return new r1(a,b,e,c,l.textContent||"",d,m)},EXa=function(a,b,c,d,e){var f=g.jq(),k=
f?g.ig("DIV"):g.ig("RUBY"),l=g.ig("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.ig("DIV"):g.ig("RP");a.textContent=b;k.appendChild(a);b=f?g.ig("DIV"):g.ig("RT");b.textContent=c;k.appendChild(b);c=e.Qe;if(10===c||11===c||12===c||13===c||14===c)if(g.Bk(b,"text-emphasis-style","filled circle"),g.Bk(b,"text-emphasis-color","currentcolor"),g.Bk(b,"webkit-text-emphasis","filled circle"),11===e.Qe||13===e.Qe)g.Bk(b,"webkit-text-emphasis-position","under left"),g.Bk(b,"text-emphasis-position","under left");c=!0;if(4===e.Qe||7===e.Qe||12===e.Qe||
14===e.Qe)g.Bk(k,"ruby-position","over"),g.Bk(k,"-webkit-ruby-position","before");else if(5===e.Qe||6===e.Qe||11===e.Qe||13===e.Qe)g.Bk(k,"ruby-position","under"),g.Bk(k,"-webkit-ruby-position","after"),c=!1;e=f?g.ig("DIV"):g.ig("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.Bk(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.Bk(f,"display","none"),f=f.nextElementSibling,g.Bk(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Bk(k.lastElementChild,"display","none"),d?(g.Bk(k,"padding-top","0.6em"),g.Bk(f,"top","0")):(g.Bk(k,"padding-bottom","0.6em"),g.Bk(f,"bottom","0")));return k},u1=function(){g.I.apply(this,arguments)},v1=function(a){u1.call(this);
this.C=a;this.pens={};this.P={};this.U={};this.D="_"+t1++;this.J={};this.B=this.j=null;this.I=!0},w1=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},x1=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},y1=function(a,b){a=w1(a,b);
return void 0!==a?a:null},A1=function(a,b){a=a.getAttribute(b);
if(null!=a)return z1.test(a),a},GXa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.U[d]:a.C);a=y1(b,"mh");null!=a&&(c.ev=a);a=y1(b,"ju");null!=a&&(c.textAlign=a);a=y1(b,"pd");null!=a&&(c.Mg=a);a=y1(b,"sd");null!=a&&(c.MJ=a);a=A1(b,"wfc");null!=a&&(c.windowColor=a);b=w1(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},HXa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.P[d]);a=y1(b,"ap");null!=a&&(c.yj=a);a=w1(b,"cc");null!=a&&(c.Po=a);a=w1(b,"ah");null!=a&&(c.zi=a);a=w1(b,"rc");null!=a&&(c.rowCount=a);b=w1(b,"av");null!=b&&(c.Zk=b);return c},IXa=function(a,b,c,d){var e={};
Object.assign(e,HXa(a,b));Object.assign(e,GXa(a,b));d?g.De(e,a.C)?(d=a.D,e=a.C):d="_"+t1++:d=b.getAttribute("id")||"_"+t1++;a=w1(b,"t")+c;b=w1(b,"d")||0x8000000000000;if(2===e.Mg||3===e.Mg)c=e.rowCount,e.rowCount=e.Po,e.Po=c;return new s1(a,b,0,d,e)},B1=function(a){u1.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},C1=function(a){a=g.Ff(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},JXa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.rowCount=a);b=b.ccColCount;void 0!==b&&(f.Po=b);if(2===f.Mg||3===f.Mg)b=f.rowCount,f.rowCount=f.Po,f.Po=b;return new s1(c,d,0,e,f)},E1=function(){this.B=this.time=this.mode=this.u=0;
this.C=new D1(this);this.D=new D1(this);this.j=[];this.clear()},LXa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Rq:a,
Mo:b,result:0};a=KXa[a];b=KXa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Mo===d;if(d)return{Rq:a,Mo:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Rq:a,Mo:b,result:2};return{Rq:a,Mo:b,result:3}},NXa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,MXa(a.C,b,c,d))},OXa=function(a,b){a.j.sort(function(e,f){var k=e.time-f.time;
return 0===k?e.order-f.order:k});
for(var c=g.r(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?NXa(a,d.PM,d.QM,b):1===d.type&&a.u&496&&MXa(a.D,d.PM,d.QM,b);a.j.length=0},F1=function(){this.type=0},G1=function(){this.state=this.Mo=this.Rq=0},PXa=function(){this.timestamp=this.j=0},H1=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new F1;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new PXa}},I1=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0===q.j||32===p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.B[k][m],q=p.j,0!==q&&(0===c&&(c=k,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},UXa=function(a,b){switch(a){case 0:return QXa[(b&127)-32];
case 1:return RXa[b&15];case 2:return SXa[b&31];case 3:return TXa[b&31]}return 0},J1=function(a){return a.B[a.row][a.u]},K1=function(a,b,c){2<=b&&1<a.u&&(--a.u,J1(a).j=0);
var d=J1(a);d.timestamp=a.D.time+0;d.j=UXa(b,c);32>a.u&&a.u++},VXa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var k=a.B[b+e][f],l=a.B[c+e][f];
k.j=l.j;k.timestamp=l.timestamp}},L1=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},M1=function(a){a.row=0<a.j?a.j:1;
a.u=1;L1(a,0,15)},N1=function(a){this.B=a;
this.D=0;this.style=new F1;this.I=new H1(this.B);this.J=new H1(this.B);this.text=new H1(this.B);this.u=this.I;this.C=this.J;this.j=this.u},O1=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(I1(d,c),M1(a.u),M1(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(I1(d,c),L1(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},WXa=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},XXa=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},D1=function(a){this.j=a;
this.D=0;this.B=new N1(this.j);this.I=new N1(this.j);this.u=new G1;this.C=this.B},MXa=function(a,b,c,d){a.u.update();
b=LXa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Rq;c=b.Mo;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&K1(a,0,b),c&96&&K1(a,0,c),0!==b&&0!==c&&3===a.style.type&&I1(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Rq=e,b.Mo=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,k=1+d-c.j;VXa(c,k,f,c.j);b=f;e=c.j;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));L1(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:K1(b.j,0,32);break a;case 48:57===c?(d=b.j,J1(d).j=0,32>d.u&&d.u++):K1(b.j,1,c&15)}break;case 2:c&32&&K1(b.j,2,c&31);break;case 3:c&32&&K1(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:WXa(b);
break;case 33:d=b.j;1<d.u&&(--d.u,J1(d).j=0);break;case 36:d=b.j;b=J1(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:O1(b,2,d);break;case 38:O1(b,3,d);break;case 39:O1(b,4,d);break;case 40:K1(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);M1(d);XXa(b);break;case 43:XXa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:I1(a,d)}L1(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;I1(a,d);VXa(a,b,b+1,a.j-1);L1(a,a.row,1)}break;case 46:L1(b.C,0,15);break;case 47:I1(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,WXa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},YXa=function(){},P1=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},Q1=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},R1=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},S1=function(a,b){u1.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new E1;this.j.u=1<<this.track},T1=function(a){if("string"===typeof a)return!1;
a=new P1(a,8,0);return ZXa(a)},ZXa=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==R1(a))return!1;
a.version=Q1(a);if(1<a.version)return!1;Q1(a);Q1(a);Q1(a);return!0},U1=function(){u1.call(this)},$Xa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3===p.nodeType)p=new r1(b,c,d,e.id,p.nodeValue,f||0<n,g.Ae(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);$Xa(a,b,c,d,e,!0,p,q,m)}}},V1=function(a){var b=a.split(":");
a=0;b=g.r(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},aYa=function(a,b,c,d){d=Object.assign({ev:0},d);
return new s1(a,b,c,"_"+t1++,d)},W1=function(a,b){g.I.call(this);
this.G=a;this.environmentData=b;this.j=null;this.u=this.G.Gu()},gYa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.u&&b){var f=e,k=bYa(a,b,d),l=[];try{for(var m=g.r(k),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.DJ;l="string"!==typeof q?l.concat(cYa(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(dYa(a,q,t)):l.concat(eYa(a,c,q,t))}var u=l}catch(x){g.R(x),a.clear(),u=[]}if(0!==u.length)return u}b=fYa(b);if(!b)return[];try{return"string"!==typeof b?cYa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?dYa(a,b,d):eYa(a,c,b,d)}catch(x){return g.R(x),a.clear(),[]}},fYa=function(a){if("string"===
typeof a||T1(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.ux(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.gx(a)},bYa=function(a,b,c){if("string"===typeof b||T1(b))return[{trackData:b,
DJ:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.sta(d);if(a.u&&e){var f=g.kta(e),k=g.lta(e);e=e.j;f&&e&&a.u.Pz(e,f,k)}f=g.Dx(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.r(f.entries());for(k=f.next();!k.done;k=f.next())e=g.r(k.value),k=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.gx(e),a.push({trackData:e,DJ:c+1E3*k});hYa(d,a,c);return a=a.filter(function(l){return!!l.trackData})},
hYa=function(a,b,c){var d=g.ux(a,0,1836476516),e=9E4;
d&&(e=g.vx(d)||9E4);d=0;var f=g.Dx(a,1836019558);f=g.r(f.entries());for(var k=f.next();!k.done;k=f.next()){var l=g.r(k.value);k=l.next().value;l=l.next().value;k<b.length&&(l=g.ux(a,l.dataOffset,1953653094))&&(l=g.ux(a,l.dataOffset,1952867444))&&(l=g.Bx(l)/e*1E3,0===k&&(d=l),b[k].DJ=l-d+c||c*k*1E3)}},cYa=function(a,b,c,d,e){if(!T1(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new S1(e,b));return a.j.u(c,d)},dYa=function(a,b,c){a.j||(a.j=new U1);
a=a.j.u(b,c);.01>Math.random()&&g.lu(Error("Deprecated subtitles format in web player: WebVTT"));return a},eYa=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new B1(iYa(b))),a.j.u(c,d)}catch(f){return g.R(f),[]}var e=g.zZ(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new v1(iYa(b),a.environmentData)),a.j.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},iYa=function(a){var b=
{};
if(a=g.FC(a))b.lang=a,g.STa.test(a)&&(b.Mg=1);return b},Z1=function(a){g.HI.call(this,a);
var b=this;this.G=a;this.environmentData=this.G.S();this.videoData=this.G.getVideoData();this.Za=this.G.Wa();this.C={Kd:{}};this.D={Kd:{}};this.ea=[];this.P={};this.Ga={};this.V=!1;this.Kb=g.ED(this.videoData);this.Sa=g.EDa(this.videoData,this.G);this.Gb=!!this.videoData.captionTracks.length;this.dc=!!this.videoData.Gc;this.Ka="3"===this.environmentData.controlsType;this.u=this.I=this.J=this.Ca=this.Ya=null;this.Pa=new W1(this.G,this.environmentData);this.j=null;this.Z=new g.Vy(this);this.Qa=new g.V({F:"div",
L:"ytp-caption-window-container",T:{id:"ytp-caption-window-container"}});var c=null,d=g.uo("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.io(d));this.storage=c;var e;this.ib=!(null==(e=a.Ed())||!e.Iz());this.B=jYa(this);this.U=!this.B&&this.Ka&&this.ib&&this.Sa;g.J(this,this.Pa);this.B?this.xa=this.ma=null:(this.ma=new g.mn(this.eK,void 0,this),g.J(this,this.ma),this.xa=new g.K(this.E0,2E3,this),g.J(this,this.xa));g.J(this,this.Z);this.environmentData.K("caption_window_container_killswitch")||
g.rI(this.player,this.Qa.element,4);g.J(this,this.Qa);this.B||this.Z.N(a,"resize",this.gK);(this.sb=!g.Nt()&&!this.G.isFullscreen()&&!this.B&&!this.U&&!this.environmentData.K("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.Z.N(a,"resize",this.uZ);this.Z.N(a,"onPlaybackAudioChange",this.HY);this.Z.N(a,g.mv("captions"),function(f){b.onCueRangeEnter(f)});
this.Z.N(a,g.nv("captions"),function(f){b.onCueRangeExit(f)});
X1(this,Y1(this)||{});this.player.Ia("captionssupportchanged")},mYa=function(a){if(1===a.environmentData.Ya||1===a.videoData.Jw||"alwayson"===g.oD(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.environmentData.Ya){var c;g.kB(a.environmentData)?c=kYa(a):c=lYa(a,"module-enabled");if(null!=c)return!!c}c=h1(a.player.getAudioTrack(),i1(a.environmentData));var d=g.oD(a.videoData,"yt:cc");if(void 0===$1(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===g.oD(a.videoData,"yt:cc")},a2=function(a,
b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},$1=function(a){var b=void 0,c=g.Jq(g.Iq.getInstance(),65);
if(g.kB(a.environmentData)&&null!=c){if(null!=kYa(a))return!1;b=!c}return b},nYa=function(a){var b;
a.Kb?b=new o1(a.environmentData,a.videoData,a.player.getAudioTrack(),a.player):a.Sa?b=new l1(a.videoData.j,a.player):a.Gb?b=new g.LI(a.environmentData,a.videoData,a.player.getAudioTrack()):b=new g.NI(a.environmentData,a.videoData.Gc,a.videoData.videoId,g.sya(a.videoData),a.videoData.ql);return b},c2=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.dc?!1:a.Gb?!1:!0);b=g.II(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.environmentData.captionsLanguagePreference,g.oD(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.FC(b[e])===c[d])return b[e];return a.I&&a.I.B?a.I.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||b2(a)}return null},b2=function(a){return a.I&&a.I.j},d2=function(a){var b=b2(a);
return!!b&&a.j===b},oYa=function(a){var b=h1(a.player.getAudioTrack(),i1(a.environmentData)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=c2(a,a.V):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&a2(a)?c=b2(a):$1(a)||a.V||mYa(a)?c=c2(a,a.V):a2(a)&&(c=b2(a));if(a.B||a.U){var d=g.II(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],k=g.ig("TRACK");k.setAttribute("kind","subtitles");k.setAttribute("label",g.DC(f));k.setAttribute("srclang",g.FC(f));k.setAttribute("id",f.toString());a.U||k.setAttribute("src",a.u.zr(f,"vtt"));f===c&&k.setAttribute("default","1");b.push(k)}c=a.G.Ed();c.Yw(b);c=c.df();
a.ib&&a.Z.N(c.textTracks,"change",a.R_)}else!a.j&&c&&e2(a,c),a.player.Ia("onCaptionsTrackListChanged"),a.player.Ia("onApiChange")},pYa=function(a,b){var c=a.G.Ed().df().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},e2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.V=c,a.V&&(g.kB(a.environmentData)?f2(a,!!b):g2(a,"module-enabled",!!b)));a.j=b;a2(a)&&(a.j=b2(a));a.load()},rYa=function(a,b){if(b instanceof s1){var c=a.P[b.id];
c&&c.u!==b&&(c.dispose(),delete a.P[b.id],c=null);c||(c=qYa(a,b))&&(a.P[b.id]=c)}else c=b.windowId,a.Ga[c]||(a.Ga[c]=[]),a.Ga[c].push(b)},sYa=function(a,b){a.environmentData.K("caption_window_container_killswitch")?g.rI(a.player,b,4):a.Qa.element.appendChild(b)},qYa=function(a,b){var c=a.Za.getVideoContentRect(!0).height,d=a.Za.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.FC(a.j):null;e&&g.STa.test(e)&&(b.params.Mg=1);e=a.Za.getPlayerSize();switch(null!=b.params.ev?b.params.ev:1<b.j.length?1:0){case 1:return new p1(b,a.C,a.D,d,c,e.width,e.height,a.environmentData.experiments);case 2:return new q1(b,a.C,a.D,d,c,e.width,e.height,a.environmentData.experiments);default:return new n1(b,a.C,a.D,d,c,e.width,e.height,a.environmentData.experiments)}},X1=function(a,b,c){c=void 0===c?!1:c;
var d=h2.Kd;a.C={};Object.assign(a.C,h2);a.C.Kd={};Object.assign(a.C.Kd,d);a.D={Kd:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;z1.test(f);e.Kd.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;z1.test(f);e.Kd.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||h2.windowColor;z1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Kd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Kd.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Kd;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Kd.textOpacity=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=h2.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Kd.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Kd.fontFamily=f;a.loaded&&a.gK();c&&(a.environmentData.K("web_player_local_storage_for_captions_setting_killswitch")?g2(a,"display-settings",b):g.Ku("yt-player-caption-display-settings",b,2592E3))},i2=function(a,b,c){b&&!a.J?(b=DXa({Mg:0,
lang:"zh-CN"}),a.J=[b,new r1(b.start,b.end-b.start,0,b.id,null!=c?c:"\u5b57\u5e55\u6837\u5f0f\u9884\u89c8")],a.player.Sd(a.J)):!b&&a.J&&(tYa(a,a.J),a.J=null)},tYa=function(a,b){a.player.Kg(b);
b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.Ob(a.ea,c.value);g.nn(a.ma)},lYa=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},g2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},f2=function(a,b){a.G.isInline()||g.Ku("yt-player-sticky-caption",b,2592E3)},kYa=function(a){if(!a.G.isInline())return g.Lu("yt-player-sticky-caption")},Y1=function(a){return a.environmentData.K("web_player_local_storage_for_captions_setting_killswitch")?lYa(a,"display-settings"):g.Lu("yt-player-caption-display-settings")},jYa=function(a){var b,c=!(null==(b=a.G.Ed())||
!b.Hz());
return a.Ka&&c&&!a.Sa};
g.AN.prototype.Hx=g.da(34,function(a){var b=2;this.xa.has(a)?b=0:g.UGa(this,a)&&(b=1);return b});
g.oQ.prototype.Hx=g.da(33,function(a){return this.Zc.Hx(a)});
g.AN.prototype.Pz=g.da(32,function(a,b,c){this.ma.set(a,{ZA:b,Ww:c})});
g.oQ.prototype.Pz=g.da(31,function(a,b,c){this.Zc.Pz(a,b,c)});
g.aJ.prototype.Zt=g.da(29,function(){for(var a=g.bg(document,"track",void 0,this.j),b=0;b<a.length;b++)g.mg(a[b])});
g.kN.prototype.Zt=g.da(28,function(){this.mediaElement.Zt()});
g.aJ.prototype.Iz=g.da(27,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.kN.prototype.Iz=g.da(26,function(){return this.mediaElement.Iz()});
g.aJ.prototype.Hz=g.da(25,function(){return!!this.j.textTracks});
g.kN.prototype.Hz=g.da(24,function(){return this.mediaElement.Hz()});
g.aJ.prototype.Yw=g.da(23,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.kN.prototype.Yw=g.da(22,function(a){this.mediaElement.Yw(a)});
g.KI.prototype.KI=g.da(21,function(){return!1});
g.KI.prototype.Hp=g.da(20,function(){});
g.LI.prototype.Hp=g.da(19,function(a,b,c){var d=this;this.isDisposed();b=this.zr(a,b);this.uo();this.j=g.Xp(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.NI.prototype.Hp=g.da(18,function(a,b,c){var d=this;this.isDisposed();b=this.zr(a,b);this.uo();this.j=g.Xp(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.dQ.prototype.Ux=g.da(8,function(){return this.J});
g.GS.prototype.Ux=g.da(7,function(){var a;return(null==(a=g.tI(this))?void 0:a.Gu())||null});
g.kI.prototype.Gu=g.da(6,function(){return this.app.Ux()});
g.gS.prototype.Gu=g.da(5,function(){var a;return(null==(a=this.Fa)?void 0:a.Ux())||null});
var oXa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",
as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgn:"Western Balochi",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",
bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",
chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",
dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",
ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",
grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",
io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",
km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",
lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",
mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",
nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",
pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",
sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",
smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",
tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",
uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",
zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};j1.prototype.contains=function(a){a=g.Wb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
j1.prototype.length=function(){return this.segments.length/2};
g.w(k1,g.I);g.h=k1.prototype;g.h.Y=function(){g.I.prototype.Y.call(this);this.B&&this.B.cancel()};
g.h.CC=function(){this.seekTo(this.player.getCurrentTime())};
g.h.seekTo=function(a){a-=this.player.pd();var b=this.j;this.j=g.Hb(this.V.yn(a).j);b!==this.j&&this.U&&this.U()};
g.h.reset=function(){this.C=new j1;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.h.WO=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Eo(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.Bw(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai){var c=this.player.Gu();if(c){var d=a.j[0].Ha;if(b=c.Ck(a.j[0].B,d,a.j[0].j.info.id,3))if(c=c.Hx(d),0===c)b&&(a.B=new g.Lw(b));else if(2===c){this.J.start();mXa(this)&&this.seekTo(this.player.getCurrentTime());return}}}a.j[0].duration?(this.C.contains(a.j[0].Ha)||
nXa(this,a),this.j=g.Hb(a.j)):!this.environmentData.K("force_caption_seek_for_live_killswitch")&&mXa(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.w(l1,g.KI);g.h=l1.prototype;g.h.Hp=function(a,b,c){var d=this;this.uo();b=qXa(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?rXa(this,b,"386"):rXa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.CDa(this.environmentData);this.B=new k1(f,this.G,b,function(k,l){c(k,a,l,e)},this.I||g.Ey(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.h.KI=function(){var a=this.D;this.D=!1;return a};
g.h.Xu=function(a){var b=this.I?[new g.CC({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.CC({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?pXa(this,"386"):pXa(this);b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.JI(this.u,c.value);a()};
g.h.uo=function(){this.B&&(this.B.dispose(),this.B=null)};
g.h.zr=function(){return""};
var z1=/^#(?:[0-9a-f]{3}){1,2}$/i,tXa=/#(.)(.)(.)/,sXa=/^#(?:[0-9a-f]{3}){1,2}$/i;var vXa=["left","right","center","justify"];g.w(n1,g.V);g.h=n1.prototype;g.h.IU=function(a,b){var c=g.Qk(this.element,this.element.parentElement);this.Sa=a-c.x;this.Ya=b-c.y;g.vn(this.element,"ytp-dragging")};
g.h.HU=function(a,b){var c=g.Sk(this.element);a=a-this.Sa-.02*this.playerWidth;var d=b-this.Ya-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Ff(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.Ff(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Ff(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.Ff(c,0,1);this.u.params.yj=b;this.u.params.Zk=c;this.u.params.zi=a;this.j.yj=b;this.j.Zk=c;this.j.zi=a;this.Ga.yj=b;this.Ga.Zk=c;this.Ga.zi=a;this.ZQ()};
g.h.GU=function(){g.xn(this.element,"ytp-dragging")};
g.h.ZQ=function(){this.Mv(this.D)};
g.h.getType=function(){return this.type};
g.h.Mv=function(a){var b=Math.min(this.MN(),this.maxWidth),c=this.LN(),d="";3===this.u.params.Mg&&(d="rotate(180deg)");g.Bk(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.pF(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.zi+2;d=this.j.yj;switch(d){case 0:case 3:case 6:(b=this.j.Kd.fontSizeIncrement)&&0<b&&2!==this.j.Mg&&3!==
this.j.Mg&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.Zk+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Bk(this.element,
a)};
g.h.pF=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.ma||this.D.length>b)b=0,this.ma=!1,this.D=[],this.I=this.Ca=this.xa=null,g.kg(this.C);for(;b<a.length;b++)zXa(this,a[b])};
g.h.MN=function(){return 0};
g.h.LN=function(){return 0};
g.h.toString=function(){return g.V.prototype.toString.call(this)};g.w(o1,g.KI);o1.prototype.Hp=function(a,b,c){kXa(this.videoData.videoId,a.vssId,c)};
o1.prototype.Xu=function(a){if(this.audioTrack)for(var b=g.r(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.JI(this.u,c.value);a()};g.w(p1,n1);p1.prototype.pF=function(a){var b=this.u.j;n1.prototype.pF.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,uYa);var e=c.j;var f=d}zXa(this,c,d)}};
var uYa={mX:!0};g.w(q1,n1);g.h=q1.prototype;g.h.ZQ=function(){g.pn(this.Pa)};
g.h.k_=function(){g.xn(this.element,"ytp-rollup-mode");this.Mv(this.sb,!0)};
g.h.LN=function(){return this.B?this.U:this.P};
g.h.MN=function(){return this.B?this.P:this.U};
g.h.Mv=function(a,b){this.sb=a;if(this.u.params.rowCount){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.Za=this.U;this.P=this.U=0;n1.prototype.Mv.call(this,a);CXa(this,b)}n1.prototype.Mv.call(this,a)};g.w(r1,g.kv);r1.prototype.toString=function(){return g.kv.prototype.toString.call(this)};g.w(s1,g.kv);s1.prototype.toString=function(){return g.kv.prototype.toString.call(this)};
var t1=0;g.w(u1,g.I);u1.prototype.u=function(){return[]};
u1.prototype.reset=function(){};g.w(v1,u1);v1.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
v1.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.r(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.r(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,k={},l=a.getAttribute("p");l&&Object.assign(k,this.pens[l]);l=x1(a,"b");
null!=l&&(k.bold=l);l=x1(a,"i");null!=l&&(k.italic=l);l=x1(a,"u");null!=l&&(k.underline=l);l=y1(a,"et");null!=l&&(k.charEdgeStyle=l);l=y1(a,"of");null!=l&&(k.offset=l);l=A1(a,"bc");null!=l&&(k.background=l);l=A1(a,"ec");null!=l&&(k.DF=l);l=A1(a,"fc");null!=l&&(k.color=l);l=y1(a,"fs");null!=l&&0!==l&&(k.fontFamily=l);l=w1(a,"sz");void 0!==l&&(k.fontSizeIncrement=l/100-1);l=w1(a,"bo");void 0!==l&&(k.backgroundOpacity=l/255);l=w1(a,"fo");void 0!==l&&(k.textOpacity=l/255);l=y1(a,"rb");null!=l&&10!==l&&
0!==l&&(k.Qe=10<l?l-1:l);a=y1(a,"hg");null!=a&&(k.pO=a);f[c]=k;break;case "ws":c=a.getAttribute("id");this.U[c]=GXa(this,a);break;case "wp":c=a.getAttribute("id"),this.P[c]=HXa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.r(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=IXa(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
k=!!x1(a,"a");l=(w1(a,"t")||0)+l;var m=w1(a,"d")||5E3;k||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=k?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var u=q[t],x=void 0;0<t&&(k=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.pens[u]:null)&&u.Qe&&(1===u.Qe?(u=q.slice(t,t+
4),4===u.length&&(x=FXa(l,m,f,k,n,u,this.pens),t+=3)):x=FXa(l,m,f,k,n,[y],this.pens)),!x){var z=y;x=l;y=m;u=f;var D=k,G=n,F=z.textContent?z.textContent:"",L=z.getAttribute("p");L=L?this.pens[L]:null;z=w1(z,"t")||0;x=new r1(x+z,y-z,G,u,F,D,L)}}else x=new r1(l,m,n,f,u.textContent||"",k,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.j=IXa(this,a,b,!0),d.push(this.j)),a=g.r(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var vYa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(B1,u1);B1.prototype.reset=function(){this.B.clear()};
B1.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.r(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},k=e.pParentId;k&&Object.assign(f,this.j.get(k));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);k=e.ofOffset;null!=k&&(f.offset=k);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);k=e.etEdgeType;null!=k&&(f.charEdgeStyle=k);void 0!==e.ecEdgeColor&&(f.DF=C1(e.ecEdgeColor));k=e.fsFontStyle;null!=k&&0!==k&&(f.fontFamily=
k);void 0!==e.fcForeColor&&(f.color=C1(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=C1(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(k=e.rbRuby)&&10!==k&&(f.Qe=10<k?k-1:k,f.Yk=vYa.get(f.Qe));e.hgHorizGroup&&(f.pO=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.r(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(k=e.wsParentId)?Object.assign(f,this.D.get(k)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.ev=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Mg=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.MJ=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=C1(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.r(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(k=e.wpParentId)&&Object.assign(f,this.C.get(k)),void 0!==e.ahHorPos&&
(f.zi=e.ahHorPos),void 0!==e.apPoint&&(f.yj=e.apPoint),void 0!==e.avVerPos&&(f.Zk=e.avVerPos),void 0!==e.ccCols&&(f.Po=e.ccCols),void 0!==e.rcRows&&(f.rowCount=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.r(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=JXa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+t1++,k=JXa(this,l,d,e,f),a.push(k),this.B.set(f,k));0===e&&(e=5E3);k=this.B.get(f);
var m=!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.j.get(t.pPenId));if(2===(null!=k.params.ev?k.params.ev:1<k.j.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.Qe)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.j.get(z))&&z.Qe&&2===z.Qe?(z=p[t+2].pPenId,z=this.j.get(z),!z||!z.Qe||3>z.Qe?t=!1:(z=p[t+3].pPenId,t=(z=this.j.get(z))&&
z.Qe&&2===z.Qe?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var D=this.j.get(p[l+2].pPenId);u=EXa(u,x,z,t,D);m=new r1(d,e,n,f,u,m,y);l+=3}else m=new r1(d+x,e-x,n,k.id,u,m,y||q);m&&(a.push(m),k.j.push(m))}m=!0}}}b=a}else b=[];return b};E1.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
E1.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var KXa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];F1.prototype.set=function(a){this.type=a};
F1.prototype.get=function(){return this.type};
G1.prototype.clear=function(){this.state=0};
G1.prototype.update=function(){this.state=2===this.state?1:0};
G1.prototype.isValid=function(){return 0!==this.state};
G1.prototype.matches=function(a,b){return this.isValid()&&a===this.Rq&&b===this.Mo};
PXa.prototype.reset=function(){this.timestamp=this.j=0};
H1.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
H1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
H1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var QXa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],RXa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],SXa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],TXa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];N1.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
D1.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};YXa.prototype.C=function(){};g.w(P1,YXa);P1.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+t1++;c=c/1E3-this.I;d=d/1E3-this.I;a=new s1(c,d-c,5,f,{textAlign:0,yj:0,zi:2.5*b,Zk:5.33*a});e=new r1(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.w(S1,u1);S1.prototype.u=function(a){a=new P1(a,a.byteLength,this.B);if(ZXa(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=R1(a)*(1E3/45):1===a.version&&(a.B=4294967296*R1(a)+R1(a)),a.D=Q1(a);0<a.D;a.D--){var b=Q1(a),c=Q1(a),d=Q1(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,PM:c,QM:d,order:b.j.length}))}OXa(this.j,a);return a.u}return[]};
S1.prototype.reset=function(){this.j.clear()};g.w(U1,u1);
U1.prototype.u=function(a,b){var c=[];a=a.split(wYa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!xYa.test(e)){var k=j2.exec(e);if(k&&4<=k.length){var l=V1(k[1]),m=V1(k[2])-l;l+=f;var n=(k=k[3])?k.split(" "):[];k={};var p=null;var q="";var t=null,u="";n=g.r(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],k.Zk=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];k.zi=Number.parseInt(t,10);2===x.length&&(u=x[1].trim());break;case "align":switch(y){case "start":k.textAlign=0;break;case "middle":k.textAlign=2;break;case "end":k.textAlign=1}}}p||q||(q="end");if(!t)switch(k.textAlign){case 0:k.zi=0;break;case 1:k.zi=100;break;case 2:k.zi=50}if(null!=k.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(k.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;k.yj=q}e=e.substring(j2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=k;k=e;e={};if(0>k.indexOf("<")&&0>k.indexOf("&"))f=aYa(l,m,5,u),m=new r1(l,m,5,f.id,k,!1,g.Ae(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=k.split(yYa),1===q.length?(k=5,u=aYa(l,m,k,u)):(p=k=6,u=Object.assign({Po:32},u),u=new s1(l,m,p,"_"+t1++,u)),c.push(u),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(x=g.zZ("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,$Xa(this,p,m-(p-l),k,u,0<t,y,e,c)):p=V1(n)+f}j2.lastIndex=0}}return c};
var xYa=/^NOTE/,wYa=/(?:\r\n|\r|\n){2,}/,j2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),yYa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.mN.TB(U1,{u:"wvppt"});g.w(W1,g.I);W1.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
W1.prototype.reset=function(){this.j&&this.j.reset()};
W1.prototype.Y=function(){g.I.prototype.Y.call(this);this.clear()};var h2={windowColor:"#080808",windowOpacity:0,textAlign:2,yj:7,zi:50,Zk:100,Kd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(Z1,g.HI);g.h=Z1.prototype;g.h.Y=function(){if(this.B||this.U){var a=this.G.Ed();a&&!a.isDisposed()&&a.Zt()}else i2(this,!1);g.HI.prototype.Y.call(this);this.player.Ia("captionssupportchanged")};
g.h.Ks=function(){if(this.Ka)return this.B||this.U;var a=h1(this.player.getAudioTrack(),i1(this.environmentData));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?a2(this):$1(this)||a2(this)?!0:mYa(this)};
g.h.load=function(){var a=this;g.HI.prototype.load.call(this);var b=!this.environmentData.K("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.j&&(this.Pa.clear(),this.B?pYa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Hp(this.j,"json3",function(c,d,e,f){c&&(a.u.KI()&&(a.ea=[],a.G.yf("captions"),g.nn(a.ma),a.Pa.reset()),c=gYa(a.Pa,c,d,e,f),a.player.Sd(c,void 0,a.Sa),!a.V||a.U||d2(a)||g.YA(a.environmentData)||g.QA(a.environmentData)||
(g.qn(a.xa),c=DXa({yj:0,zi:5,Zk:5,rowCount:2,textAlign:0,Mg:0,lang:"zh-CN"}),a.Ca=[c],d=["\u70b9\u51fb "," \u67e5\u770b\u8bbe\u7f6e"],a.Ya||(e=new g.aG(g.rG()),g.J(a,e),a.Ya=e.element),e=c.end-c.start,(f=g.DC(a.j))&&a.Ca.push(new r1(c.start,e,0,c.id,f)),a.Ca.push(new r1(c.start,e,0,c.id,d[0]),new r1(c.start,e,0,c.id,a.Ya,!0),new r1(c.start,e,0,c.id,d[1],!0)),a.player.Sd(a.Ca),g.on(a.xa)),!a.V||a.U||d2(a)||(g.kB(a.environmentData)?f2(a,!0):g2(a,"module-enabled",!0),a.I&&(a.I.C=a.j),a.player.Vs()),
a.V=!1)}),!b||this.B||this.U||d2(this)||this.player.Ia("captionschanged",g.EC(this.j))),b||(this.j&&!d2(this)?this.player.Ia("captionschanged",g.EC(this.j)):this.player.Ia("onCaptionsTrackListChanged"))):(this.u=nYa(this),g.J(this,this.u),this.u.Xu(function(){oYa(a)}))};
g.h.unload=function(){this.B&&this.j?pYa(this,!1):(this.xa&&g.qn(this.xa),this.player.yf("captions"),this.ea=[],this.u&&this.u.uo(),this.Pa.clear(),this.J&&this.player.Sd(this.J),this.gK());g.HI.prototype.unload.call(this);this.player.Vs();this.player.Ia("captionschanged",{})};
g.h.create=function(){this.Ks()&&this.load()};
g.h.R_=function(){for(var a=this.G.Ed().df().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=g.II(this.u.u,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.j:null)!==b&&e2(this,b,!0)};
g.h.M1=function(){!this.j&&this.B||this.unload()};
g.h.onCueRangeEnter=function(a){this.ea.push(a);g.nn(this.ma)};
g.h.onCueRangeExit=function(a){g.Ob(this.ea,a);this.u instanceof l1&&this.u.I&&this.player.Kg([a]);g.nn(this.ma)};
g.h.getCaptionWindowContainerId=function(){return this.Qa.element.id};
g.h.E0=function(){tYa(this,this.Ca);this.Ca=null};
g.h.eK=function(){var a=this;if(!this.sb||!this.B){this.ma.stop();g.qca(this.Ga);this.ea.sort(g.lv);var b=this.ea;if(this.J){var c=g.Cl(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.r(b);for(c=b.next();!c.done;c=b.next())rYa(this,c.value);b={};c=g.r(Object.entries(this.P));for(var d=c.next();!d.done;b={oq:b.oq,jk:b.jk},d=c.next()){var e=g.r(d.value);d=e.next().value;e=e.next().value;b.oq=d;b.jk=e;this.Ga[b.oq]?(b.jk.element.parentNode||(b.jk instanceof q1||b.jk instanceof p1||g.qe(this.P,function(f){return function(k,l){l!==f.oq&&k.u.params.yj===f.jk.u.params.yj&&k.u.params.zi===f.jk.u.params.zi&&k.u.params.Zk===f.jk.u.params.Zk&&(k.dispose(),delete a.P[l]);
return l===f.oq}}(b),this),sYa(this,b.jk.element)),b.jk.Mv(this.Ga[b.oq])):(b.jk.dispose(),delete this.P[b.oq])}}};
g.h.I0=function(){X1(this,{},!0);this.environmentData.K("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Ia("captionssettingschanged")};
g.h.JW=function(){var a=h2.Kd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:h2.windowColor,windowOpacity:h2.windowOpacity};var b=Y1(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.dS=function(a,b){var c={};Object.assign(c,Y1(this));Object.assign(c,a);X1(this,c,b);this.player.Ia("captionssettingschanged")};
g.h.gK=function(){!this.B&&this.loaded&&(g.ne(this.P,function(a,b){a.dispose();delete this.P[b]},this),this.eK())};
g.h.Wf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Ff(b,-2,4);this.dS({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&e2(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.environmentData.B&&(g.kB(this.environmentData)?f2(this,!!b):g2(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Na(b))break;if(g.Ae(b)){e2(this,null,!0);break}a=g.II(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||
c&&e.languageName!==b.languageName||(c=b.translationLanguage?jXa(e,b.translationLanguage):e)}!c||c===this.j&&this.loaded||(b=g.ova(),a=g.FC(c),b.length&&a===b[b.length-1]||(b.push(a),g.Ku("yt-player-caption-language-preferences",b)),e2(this,c,!0))}else return this.loaded&&this.j&&!d2(this)?g.EC(this.j):{};return"";case "tracklist":return this.u?g.Rj(g.II(this.u.u,!(!b||!b.includeAsr)),function(f){return g.EC(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.B||void 0===b||i2(this,!!b);break;case "sampleSubtitlesCustomized":this.B||i2(this,!!b,b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.environmentData.B&&a.push("stickyLoading");return a};
g.h.JG=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.environmentData.K("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.FC(a));return{cc:b}}return{}};
g.h.B1=function(){this.loaded&&this.j&&!d2(this)?(g.kB(this.environmentData)?f2(this,!1):g2(this,"module-enabled",!1),this.unload(),a2(this,!0)&&e2(this,b2(this),!1)):this.JR()};
g.h.JR=function(){this.loaded&&this.j&&!d2(this)||e2(this,d2(this)||!this.j?c2(this,!0):this.j,!0)};
g.h.HY=function(){var a=d2(this);a2(this,a)?e2(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Ks()&&(a?e2(this,c2(this),!1):this.load()))};
g.h.uZ=function(){var a=this.G.Ed();a&&!a.isDisposed()&&a.Zt();this.G.isFullscreen()?(this.B=this.Ka=!0,this.loaded&&oYa(this)):(this.Ka="3"===this.environmentData.controlsType,this.B=jYa(this));e2(this,this.j)};
g.mN.TB(Z1,{eK:"smucd"});g.GI("captions",Z1);})(_yt_player);
